Update Makefile for bugo conflict
No VM guests are running outdated hypervisor (qemu) binaries on this host.
sudo pip3 install hugo==0.124.1
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.